# vim: ts=2
---
- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
    
  
  vars:
    vHome: /home/vagrant
      
  tasks:

  - include_role:
      name: gitlab

  - include_role:
      name: docker

  - name: install the GitLab Runner
    shell: curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash
    args:
      warn: no

    

  

